import { Profile, HistoryEntry, Job, TaskTemplate, ProfileId } from "./types";

export const PROFILES: Record<ProfileId, Profile> = {
  sophie: {
    id: "sophie",
    initials: "SC",
    name: "Sophie Clarke",
    role: "Cleaner",
    phone: "+44 7700 900123",
    email: "sophie@merrycleaners.co.uk",
    zone: "North London",
    since: "March 2023",
    completed: 14,
    pending: 2,
    rate: "97%",
    jobs: ["j1", "j3"],
  },
  james: {
    id: "james",
    initials: "JO",
    name: "James Osei",
    role: "Cleaner",
    phone: "+44 7700 900456",
    email: "james@merrycleaners.co.uk",
    zone: "East London",
    since: "July 2022",
    completed: 28,
    pending: 1,
    rate: "99%",
    jobs: ["j2"],
  },
  amara: {
    id: "amara",
    initials: "AN",
    name: "Amara Nwosu",
    role: "Cleaner",
    phone: "+44 7700 900789",
    email: "amara@merrycleaners.co.uk",
    zone: "South London",
    since: "January 2024",
    completed: 7,
    pending: 3,
    rate: "93%",
    jobs: ["j4"],
  },
  manager: {
    id: "manager",
    initials: "RD",
    name: "Rachel Davies",
    role: "Manager",
    phone: "+44 7700 900001",
    email: "rachel@merrycleaners.co.uk",
    zone: "All Zones",
    since: "September 2021",
    completed: 0,
    pending: 0,
    rate: "—",
    jobs: ["j1", "j2", "j3", "j4"],
  },
};

export const HISTORY: Record<ProfileId, HistoryEntry[]> = {
  sophie: [
    { name: "The Dorchester Suite 12", date: "14 Jun 2026", pct: 100, done: true },
    { name: "Finchley Road Apartment", date: "10 Jun 2026", pct: 100, done: true },
    { name: "Mayfair Townhouse", date: "5 Jun 2026", pct: 88, done: false },
    { name: "Barnet Family Home", date: "1 Jun 2026", pct: 100, done: true },
  ],
  james: [
    { name: "Canary Wharf Office", date: "16 Jun 2026", pct: 100, done: true },
    { name: "Shoreditch Studio", date: "11 Jun 2026", pct: 100, done: true },
    { name: "Stratford AirBnB", date: "8 Jun 2026", pct: 100, done: true },
  ],
  amara: [
    { name: "Brixton Flat", date: "13 Jun 2026", pct: 100, done: true },
    { name: "Clapham Terrace", date: "7 Jun 2026", pct: 75, done: false },
    { name: "Peckham Office Unit", date: "3 Jun 2026", pct: 100, done: true },
  ],
  manager: [
    { name: "Portfolio review — All sites", date: "18 Jun 2026", pct: 100, done: true },
    { name: "Q2 Inspection Round", date: "15 Jun 2026", pct: 100, done: true },
  ],
};

export const JOBS: Record<string, Job> = {
  j1: {
    id: "j1",
    name: "Finchley Road Apartment",
    address: "42 Finchley Road, London NW3 6PE",
    date: "Fri 20 Jun 2026",
    cleaner: "Sophie Clarke",
    type: "deep",
  },
  j2: {
    id: "j2",
    name: "Canary Wharf Office Suite",
    address: "Level 8, 10 Canada Sq, London E14 5AB",
    date: "Fri 20 Jun 2026",
    cleaner: "James Osei",
    type: "standard",
  },
  j3: {
    id: "j3",
    name: "Mayfair Townhouse",
    address: "7 Park Lane, London W1K 1QS",
    date: "Sat 21 Jun 2026",
    cleaner: "Sophie Clarke",
    type: "deep",
  },
  j4: {
    id: "j4",
    name: "Clapham Junction AirBnB",
    address: "18 Lavender Hill, London SW11 1LJ",
    date: "Sat 21 Jun 2026",
    cleaner: "Amara Nwosu",
    type: "standard",
  },
};

export const DEEP_TASKS: TaskTemplate = {
  "🛋 Living Room": [
    "Dust all surfaces including skirting boards and cornices",
    "Vacuum sofas, cushions and under furniture",
    "Clean windows and window sills inside",
    "Wipe light switches, sockets and door frames",
    "Deep clean carpets or mop hard floors",
    "Clean mirrors and glass surfaces streak-free",
    "Remove cobwebs from corners and ceilings",
    "Polish wooden furniture",
    "Clean behind and under sofa",
    "Wipe radiators and grilles",
  ],
  "🍳 Kitchen": [
    "Deep clean oven interior including racks and door glass",
    "Degrease extractor fan and filter",
    "Clean inside fridge — shelves, drawers and seal",
    "Wipe inside and outside of microwave",
    "Descale kettle and clean coffee machine",
    "Scrub sink, taps and draining board",
    "Wipe all cabinet doors and handles",
    "Clean splashback and tiles behind hob",
    "Disinfect countertops and work surfaces",
    "Mop floor and clean grout lines",
    "Empty and clean bin",
  ],
  "🛏 Bedroom": [
    "Dust all furniture including bedside tables",
    "Wipe wardrobes inside and outside",
    "Clean under bed (vacuum and wipe)",
    "Vacuum mattress and flip if required",
    "Change and launder bed linen",
    "Clean mirrors and glass",
    "Dust lampshades and light fittings",
    "Wipe light switches and door handles",
    "Vacuum or mop floors including under furniture",
    "Remove cobwebs from ceilings",
  ],
  "🚿 Bathroom": [
    "Descale and disinfect toilet bowl, seat and cistern",
    "Scrub shower tray, walls and screen/curtain",
    "Descale taps, shower head and fittings",
    "Clean bath — including taps, overflow and plug",
    "Wipe sink, basin cabinet and mirror",
    "Regrout or scrub tile grout",
    "Clean extractor fan grille",
    "Mop floor and disinfect thoroughly",
    "Empty and clean bin",
    "Polish chrome fittings",
    "Replace toiletries if required",
  ],
  "🪟 Hallway & Stairs": [
    "Vacuum stairs and edges",
    "Wipe banister and handrail",
    "Clean front door inside and out",
    "Dust skirting boards along hallway",
    "Mop hard floor in hallway",
    "Wipe light switches and door bells",
  ],
};

export const STANDARD_TASKS: TaskTemplate = {
  "🛋 Living Room": [
    "Dust all surfaces",
    "Vacuum carpet or mop floor",
    "Clean mirrors",
    "Empty bins",
    "Tidy and straighten cushions",
  ],
  "🍳 Kitchen": [
    "Wipe down countertops and hob",
    "Clean sink and taps",
    "Wipe exterior of appliances",
    "Empty and reline bin",
    "Sweep and mop floor",
  ],
  "🛏 Bedroom": [
    "Dust surfaces and furniture",
    "Vacuum or mop floor",
    "Straighten bed and change linen if required",
    "Empty bins",
  ],
  "🚿 Bathroom": [
    "Clean toilet, seat and cistern",
    "Wipe sink and taps",
    "Clean shower or bath",
    "Mop floor",
    "Restock toilet roll if needed",
    "Empty bin",
  ],
  "🪟 Hallway": ["Sweep or vacuum hallway", "Wipe surfaces"],
};

export function tasksForJob(job: Job): TaskTemplate {
  return job.type === "deep" ? DEEP_TASKS : STANDARD_TASKS;
}
